version: "3"

tasks:
  generate_proto:
    desc: Generate gRPC code
    cmds:
      - which protoc
      - protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative lib/proto/msg_source/source.proto
